version: '3.4'
services:
    db:
        image: mysql:5.7
        volumes:
          - "./.data/db:/var/lib/mysql"
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_db
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        ports:
          - "3306:3306"
    php:
        build: 
            context: docker/php-fpm
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./laravel:/var/www/laravel:cached
            - ./logs/laravel:/var/www/laravel/storage/logs:cached
        links:
            - db
        extra_hosts:
            - "docker.host:127.0.0.1"
    nginx:
        build: 
            context: docker/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        links:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./laravel:/var/www/lavarel:cached
    elk:
        image: willdurand/elk
        ports:
            - "8081:80"
        volumes:
            - ./elk/docker/elk/logstash:/etc/logstash:cached
            - ./elk/docker/elk/logstash/patterns:/opt/logstash/patterns:cached
            - ./logs/laravel:/var/www/laravel/storage/logs:cached
            - ./logs/nginx:/var/log/nginx:cached

